=== luigiLB800/luigiLB800.github.io/lm/tema7/xml-xsd/bloque1-1/actividad4/mensaje.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="mensaje">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="origen" minOccurs="0" maxOccurs="unbounded">
            <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="ciudad" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            </xs:complexType>
            </xs:element>
        <xs:element name="destino" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                <xs:sequence>
                  <xs:element name="nombre" minOccurs="0" maxOccurs="unbounded"/>
                  <xs:element name="ciudad" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
          </xs:complexType>
          </xs:element>
              <xs:element name="asunto" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
              </xs:sequence>
      </xs:complexType>
  </xs:element>
</xs:schema>

=== luigiLB800/luigiLB800.github.io/lm/tema7/xml-xsd/bloque1-1/actividad4/mensaje.XML
<?xml version="1.0" encoding="UTF-8"?>
<mensaje xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="mensaje.xsd">
<origen>
<nombre>AnaSanzTin</nombre>
<ciudad>Pamplona</ciudad>
</origen>
<destino>
<nombre>IkerRubioMol</nombre>
<ciudad>Sevilla</ciudad>
</destino>
<asunto>¡Vuelvepronto!</asunto>
</mensaje>
