<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE raiz [
<!ELEMENT raiz (partido*)>
<!ELEMENT partido (local,visitante)>
<!ELEMENT local (nombre,goles)>
<!ELEMENT visitante (nombre,goles)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT goles (#PCDATA)>
]>
<raiz>
<partido>
<local>
<nombre>Nottingham Presa</nombre>
<goles>0</goles>
</local>
<visitante>
<nombre>Inter de Mitente</nombre>
<goles>1</goles>
</visitante>
</partido>
<partido>
<local>
<nombre>Vodka Juniors</nombre>
<goles>3</goles>
</local>
<visitante>
<nombre>Sparta da Risa</nombre>
<goles>3</goles>
</visitante>
</partido>
<partido>
<local>
<nombre>Water de Múnich</nombre>
<goles>4</goles>
</local>
<visitante>
<nombre>Esteaua es del grifo</nombre>
<goles>2</goles>
</visitante>
</partido>
</raiz>